load:
  vus: 8
  duration: 2h
  sleepSeconds: 1

targets:
  - http://app-healthy-app.app.svc.cluster.local
  - http://app-slow-db-app.app.svc.cluster.local
  - http://app-error-app.app.svc.cluster.local
  - http://app-db-failure-app.app.svc.cluster.local
