image:
  repository: grafana/k6
  tag: "0.54.0"
  pullPolicy: IfNotPresent

load:
  vus: 6
  duration: 1h
  sleepSeconds: 1

targets:
  - http://app-healthy-app.app.svc.cluster.local
  - http://app-slow-db-app.app.svc.cluster.local
  - http://app-error-app.app.svc.cluster.local
  - http://app-db-failure-app.app.svc.cluster.local

resources: {}
